name: laravel_CD

on:
  workflow_run:
    workflows: ["laravel_CI"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: check out code
        uses: actions/checkout@v3

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2

      - name: login to docker
        uses: docker/login-action@v2
        with:
          username: kiddo9
          password: dckr_pat_nTW20iR4qt6Qf7zk76AntmBbVGg

      - name: build image and deploy
        uses: docker/build-push-action@v4
        with:
          file: ./Dockerfile
          push: true
          tags: kiddo9/myservices:latest
